-- MySQL Script generated by MySQL Workbench
-- 09/11/15 11:14:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sislabweb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sislabweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sislabweb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sislabweb` ;

-- -----------------------------------------------------
-- Table `sislabweb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sislabweb`.`CLIENTE` (
  `Id` INT NULL AUTO_INCREMENT COMMENT 'Código do Cliente',
  `Nome` TEXT NULL COMMENT 'Nome do cliente\n',
  `Cpf` CHAR(14) NULL,
  `Cnpj` CHAR(18) NULL,
  `Fone` TEXT NULL COMMENT 'Numero telefone fixo do cliente\n',
  `Endereco` TEXT NULL COMMENT 'Endereço do cliente\n',
  `Fax` TEXT NULL COMMENT 'Numero de fax do cliente',
  `Celular` TEXT NULL COMMENT 'Numero de telefone do cliente',
  `Email` TEXT NULL COMMENT 'Email do cliente\n',
  `Cep` TEXT NULL COMMENT 'Cep do Cliente\n',
  `Cidade` TEXT NULL COMMENT 'Cidade do cliente\n',
  `Estado` CHAR(2) NULL COMMENT 'Estado de origem do cliente (UF)\n',
  `Nome_propriedade` VARCHAR(45) NULL,
  `Area_propriedade` VARCHAR(45) NULL,
  `Localidade_propriedade` VARCHAR(45) NULL,
  `Municipio_propriedade` VARCHAR(45) NULL,
  `Estado_propriedade` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Cpf_UNIQUE` (`Cpf` ASC),
  UNIQUE INDEX `Cnpj_UNIQUE` (`Cnpj` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sislabweb`.`PESQUISADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sislabweb`.`PESQUISADOR` (
  `Login` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NULL,
  `Data_cadastro` DATETIME NULL,
  `Data_ultimo_acesso` DATETIME NULL,
  `Id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Id`, `Login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sislabweb`.`CULTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sislabweb`.`CULTURA` (
  `Nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sislabweb`.`SISTEMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sislabweb`.`SISTEMA` (
  `Nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sislabweb`.`BOLETIM_SOLO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sislabweb`.`BOLETIM_SOLO` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Pesquisa` TINYINT(1) NULL,
  `Data_entrada` VARCHAR(11) NULL,
  `Id_cliente` INT NULL,
  `Valor` DECIMAL(4,2) NULL,
  `Observacao` VARCHAR(45) NULL,
  `Cultura` VARCHAR(20) NULL,
  `Sistema` VARCHAR(30) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_BOLETIM_CLIENTE1_idx` (`Id_cliente` ASC),
  INDEX `fk_BOLETIM_SOLO_Cultura1_idx` (`Cultura` ASC),
  INDEX `fk_BOLETIM_SOLO_Sistema1_idx` (`Sistema` ASC),
  CONSTRAINT `fk_BOLETIM_CLIENTE1`
    FOREIGN KEY (`Id_cliente`)
    REFERENCES `sislabweb`.`CLIENTE` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BOLETIM_SOLO_Cultura1`
    FOREIGN KEY (`Cultura`)
    REFERENCES `sislabweb`.`CULTURA` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BOLETIM_SOLO_Sistema1`
    FOREIGN KEY (`Sistema`)
    REFERENCES `sislabweb`.`SISTEMA` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sislabweb`.`SOLO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sislabweb`.`SOLO` (
  `Id` INT NULL AUTO_INCREMENT,
  `Phcacl2` VARCHAR(45) NULL,
  `Al` VARCHAR(45) NULL,
  `Ca` VARCHAR(45) NULL,
  `Mg` VARCHAR(45) NULL,
  `Hal3` VARCHAR(45) NULL,
  `Kmgdm3` VARCHAR(45) NULL,
  `Fator` VARCHAR(45) NULL,
  `Presin` VARCHAR(45) NULL,
  `Cu` VARCHAR(45) NULL,
  `Fe` VARCHAR(45) NULL,
  `Mn` VARCHAR(45) NULL,
  `Zn` VARCHAR(45) NULL,
  `B` VARCHAR(45) NULL,
  `Normalidade` VARCHAR(45) NULL,
  `Massa` VARCHAR(45) NULL,
  `Vol_gasto` VARCHAR(45) NULL,
  `Dicromato` VARCHAR(45) NULL,
  `Toc` VARCHAR(45) NULL,
  `Leitura1` VARCHAR(45) NULL,
  `Temp1` VARCHAR(45) NULL,
  `Leitura2` VARCHAR(45) NULL,
  `Temp2` VARCHAR(45) NULL,
  `Pmehl` VARCHAR(45) NULL,
  `Data_cadastro` TIMESTAMP NULL,
  `Identificao` VARCHAR(45) NULL,
  `Rotina` TINYINT(1) NULL,
  `Mo` TINYINT(1) NULL,
  `Micro` TINYINT(1) NULL,
  `Textura` TINYINT(1) NULL,
  `Pesquisador` VARCHAR(45) NULL,
  `Id_boletim` INT NULL,
  INDEX `fk_SOLO_PESQUISADOR1_idx` (`Pesquisador` ASC),
  INDEX `fk_SOLO_BOLETIM1_idx` (`Id_boletim` ASC),
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_SOLO_PESQUISADOR1`
    FOREIGN KEY (`Pesquisador`)
    REFERENCES `sislabweb`.`PESQUISADOR` (`Login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOLO_BOLETIM1`
    FOREIGN KEY (`Id_boletim`)
    REFERENCES `sislabweb`.`BOLETIM_SOLO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sislabweb`.`PARTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sislabweb`.`PARTE` (
  `Nome` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sislabweb`.`BOLETIM_PLANTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sislabweb`.`BOLETIM_PLANTA` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Data_entrada` INT NULL,
  `Pesquisa` TINYINT(1) NULL,
  `Cultura` VARCHAR(45) NULL,
  `Observacao` VARCHAR(45) NULL,
  `Id_cliente` INT NULL,
  `Valor` DECIMAL(4,2) NULL,
  `Parte` VARCHAR(40) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_BOLETIM_PLANTA_CLIENTE1_idx` (`Id_cliente` ASC),
  INDEX `fk_BOLETIM_PLANTA_Parte1_idx` (`Parte` ASC),
  CONSTRAINT `fk_BOLETIM_PLANTA_CLIENTE1`
    FOREIGN KEY (`Id_cliente`)
    REFERENCES `sislabweb`.`CLIENTE` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BOLETIM_PLANTA_Parte1`
    FOREIGN KEY (`Parte`)
    REFERENCES `sislabweb`.`PARTE` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sislabweb`.`PLANTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sislabweb`.`PLANTA` (
  `Id` INT NULL AUTO_INCREMENT,
  `Fator` VARCHAR(45) NULL,
  `Vol_gasto` VARCHAR(45) NULL,
  `P` VARCHAR(45) NULL,
  `K` VARCHAR(45) NULL,
  `Ca` VARCHAR(45) NULL,
  `Mg` VARCHAR(45) NULL,
  `S` VARCHAR(45) NULL,
  `Cu` VARCHAR(45) NULL,
  `Fe` VARCHAR(45) NULL,
  `Mn` VARCHAR(45) NULL,
  `Zn` VARCHAR(45) NULL,
  `B` VARCHAR(45) NULL,
  `Data_cadastro` TIMESTAMP NULL,
  `Pesquisador` VARCHAR(45) NULL,
  `Id_boletim` INT NULL,
  `Micro` TINYINT(1) NULL,
  `Macro` TINYINT(1) NULL,
  `Somente_n` TINYINT(1) NULL,
  `Identificacao` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_PLANTA_PESQUISADOR1_idx` (`Pesquisador` ASC),
  INDEX `fk_PLANTA_BOLETIM_PLANTA1_idx` (`Id_boletim` ASC),
  CONSTRAINT `fk_PLANTA_PESQUISADOR1`
    FOREIGN KEY (`Pesquisador`)
    REFERENCES `sislabweb`.`PESQUISADOR` (`Login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLANTA_BOLETIM_PLANTA1`
    FOREIGN KEY (`Id_boletim`)
    REFERENCES `sislabweb`.`BOLETIM_PLANTA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
